# Generated by Django 5.1.4 on 2024-12-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('outstanding_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_network.contacts', verbose_name='contacts')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='electronic_network.networknode')),
            ],
            options={
                'verbose_name': 'Network Node',
                'verbose_name_plural': 'Network Nodes',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic_network.networknode')),
                ('level', models.PositiveIntegerField(default=2)),
            ],
            bases=('electronic_network.networknode',),
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic_network.networknode')),
                ('level', models.PositiveIntegerField(default=0)),
            ],
            bases=('electronic_network.networknode',),
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic_network.networknode')),
                ('level', models.PositiveIntegerField(default=1)),
            ],
            bases=('electronic_network.networknode',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='electronic_network.networknode')),
            ],
        ),
        migrations.AddField(
            model_name='networknode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic_network.product', verbose_name='product'),
        ),
    ]
